### ISSUE TITLE
Error in GCI skript

### ISSUE THREAD

**Issue by WarLord211** [RagnarDa/DCS-Mission-Scripts#1]
Hi im using that skript in one of my missions:
i have 4 plane groups:
TU22_CVN divertable 
TU22_CVN divertable #001
TU22_CVN divertable #002
TU22_CVN divertable #003

spawned via late activation and 10 sec later skript will loaded.

im using mist_4_4_83.lua

after spawning i got the error:
![2020-05-27](https://user-images.githubusercontent.com/10798954/83072426-0988dd80-a06f-11ea-9e19-00045ed64fac.png)

the mentioned lua is mist

**Comment by RagnarDa** [comment]
The GCI script doesn’t use MIST and the script is only 1998 lines long so the error is not in the the GCI script

**Comment by WarLord211** [comment]
why is MIST integraded in the example mission? when its not used

**Comment by RagnarDa** [comment]
Oh my bad. It was almost 7 years ago I last looked at this script... :)

" spawned via late activation"

Maybe try without having late activation for the divertables? The
instructions for the script doesnt mention late activation for divertables
so maybe it doesnt support it?

Den fre 12 juni 2020 kl 15:13 skrev Sven <notifications@github.com>:
